# Site settings
title: Connor Hammond
email: connor.hammond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Deep Thoughts with Connor Hammond
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Connor_Hammond
github_username:  ConnorH2582

# Build settings
markdown: kramdown
