# Site settings
title: Connor Hammond
email: connor.hammond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Deep Thoughts with The ConMan
baseurl: "ConnorH2582.github.io" # the subpath of your site, e.g. /blog/
url: http://ConnorH2582.github.io # the base hostname & protocol for your site
twitter_username:
github_username:  ConnorH2582

# Build settings
markdown: kramdown
